<a href="https://colab.research.google.com/github/jfink09/Deep-Learning/blob/main/00_PyTorch_Fundamentals_Video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00 PyTroch Fundamentals

resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [2]:
import torch
print(torch.__version__) # Version 1.12 and Cuda 11.3

1.12.1+cu113


## Introduction to tensors

Tesors - a way to represent numerical data

PyTorch tensors are created using `torch.Tensor()` (https://pytorch.org/docs/stable/tensors.html)

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim # Scalars are a single number and do not have dimensions

0

In [5]:
scalar.item() # Get tensor back as Python int

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim # Vectors have one dimension

1

In [8]:
vector.shape # 2 elements in vector

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])

In [10]:
MATRIX.ndim # Two brackets

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape # One 3x3 matrix

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

NNs learn by starting with tensors full of random numbers and they adjust the random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3843, 0.5674, 0.9497, 0.9019],
        [0.8609, 0.8398, 0.7645, 0.8215],
        [0.1239, 0.7481, 0.2243, 0.4088]])

In [18]:
# Create random tensor with shape similar to image tensor
# Can use size=() or not including it creates similar tensors (size is not needed)
random_image_tensor = torch.rand(size=(224,224,3)) # Height, Width, Color Channel
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.range() if there is a depricated message use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the big three errors commonly run into in PyTorch and deep learning:

1. Tensors not the right datatype
2. Tensors not the right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Single-precision_floating-point_format

In [26]:
# Float 32 tensor (how much detail about the number is stored)
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype=torch.float16, # What datatype the tensor is (float16, float32, etc.)
                                device=None,         # What device is the tensor on, "cpu" by default (cand do "cuda")
                                requires_grad=False) # PyTorch can track the gradient of the tensor when it goes through calculations
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
# Convert float 32 into float 16 (good way to fix an error for a tensor being the wrong datatype)
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [29]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [30]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

1. Tensors not the right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not the right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [31]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0976, 0.0927, 0.5284, 0.1901],
        [0.3880, 0.8132, 0.0381, 0.8599],
        [0.7119, 0.3713, 0.4214, 0.3404]])

In [32]:
some_tensor.size() # Function/method with ()
some_tensor.shape  # Attribute

torch.Size([3, 4])

In [33]:
# Find some details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}") # torch.float32 is default
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is on: {some_tensor.device}") # CPU is default

tensor([[0.0976, 0.0927, 0.5284, 0.1901],
        [0.3880, 0.8132, 0.0381, 0.8599],
        [0.7119, 0.3713, 0.4214, 0.3404]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [34]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply tensor
tensor * 10

tensor([10, 20, 30])

In [36]:
# Subtract
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out PyTorch in-built functions
torch.mul(tensor,10), torch.multiply(tensor,10)

(tensor([10, 20, 30]), tensor([10, 20, 30]))

In [38]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two ways of performing matrix multiplication in NNs and deep learning:

      1. Element-wise Multiplication
      2. Matrix multiplication (dot product)

Two main rules for matrix multiplication 
1. The **inner dimensions** must match:
    * `(n,m) @ (m,n)` Can use @ or matmul
2. The resulting matrix has the shape of the **outer dimensions**:
    * `(n,m) @ (m,n) = (n,n)`

In [39]:
# Element-wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [40]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [41]:
tensor

tensor([1, 2, 3])

In [42]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3
tensor @ tensor

tensor(14)

In [43]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.62 ms, sys: 112 µs, total: 1.73 ms
Wall time: 4.07 ms


In [44]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 2.76 ms, sys: 0 ns, total: 2.76 ms
Wall time: 3.4 ms


tensor(14)

### One of the most common errors in deep learning - shape errors

In [45]:
# Shapes for multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

#Trying matrix multiplication on these two tensors will not work due to shapes, so transpose one of them
torch.mm(tensor_A,tensor_B.T) # torch.mm is an alias for torch.matmul (same thing)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [47]:
# Matrix multiplication with correct shapes
print(f"The original shapes: Tensor_A = {tensor_A.shape}, Tensor_B = {tensor_B.shape}")
print(f"The new sahapes: Tensor_A = {tensor_A.shape} (same shape), Tensor_B = {tensor_B.T.shape} (transpose of tensor_B)")
print("The output is:\n")
output = torch.mm(tensor_A,tensor_B.T)
print(output)
print(f"\nThe output shape is: {output.shape}")

The original shapes: Tensor_A = torch.Size([3, 2]), Tensor_B = torch.Size([3, 2])
The new sahapes: Tensor_A = torch.Size([3, 2]) (same shape), Tensor_B = torch.Size([2, 3]) (transpose of tensor_B)
The output is:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

The output shape is: torch.Size([3, 3])
