<a href="https://colab.research.google.com/github/jfink09/Deep-Learning/blob/main/00_PyTorch_Fundamentals_Video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00 PyTroch Fundamentals

resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [2]:
import torch
print(torch.__version__) # Version 1.12 and Cuda 11.3

1.12.1+cu113


## Introduction to tensors

Tesors - a way to represent numerical data

PyTorch tensors are created using `torch.Tensor()` (https://pytorch.org/docs/stable/tensors.html)

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim # Scalars are a single number and do not have dimensions

0

In [5]:
scalar.item() # Get tensor back as Python int

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim # Vectors have one dimension

1

In [8]:
vector.shape # 2 elements in vector

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])

In [10]:
MATRIX.ndim # Two brackets

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape # One 3x3 matrix

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

NNs learn by starting with tensors full of random numbers and they adjust the random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2133, 0.9711, 0.6374, 0.3534],
        [0.9867, 0.1884, 0.9121, 0.6024],
        [0.3829, 0.1419, 0.5085, 0.7215]])

In [18]:
# Create random tensor with shape similar to image tensor
# Can use size=() or not including it creates similar tensors (size is not needed)
random_image_tensor = torch.rand(size=(224,224,3)) # Height, Width, Color Channel
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.range() if there is a depricated message use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the big three errors commonly run into in PyTorch and deep learning:

1. Tensors not the right datatype
2. Tensors not the right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Single-precision_floating-point_format

In [26]:
# Float 32 tensor (how much detail about the number is stored)
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype=torch.float16, # What datatype the tensor is (float16, float32, etc.)
                                device=None,         # What device is the tensor on, "cpu" by default (cand do "cuda")
                                requires_grad=False) # PyTorch can track the gradient of the tensor when it goes through calculations
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
# Convert float 32 into float 16 (good way to fix an error for a tensor being the wrong datatype)
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [29]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [30]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

1. Tensors not the right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not the right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [31]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3733, 0.4120, 0.5143, 0.2167],
        [0.0478, 0.1380, 0.7938, 0.6874],
        [0.2695, 0.0808, 0.6685, 0.0481]])

In [32]:
some_tensor.size() # Function/method with ()
some_tensor.shape  # Attribute

torch.Size([3, 4])

In [33]:
# Find some details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}") # torch.float32 is default
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is on: {some_tensor.device}") # CPU is default

tensor([[0.3733, 0.4120, 0.5143, 0.2167],
        [0.0478, 0.1380, 0.7938, 0.6874],
        [0.2695, 0.0808, 0.6685, 0.0481]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [34]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply tensor
tensor * 10

tensor([10, 20, 30])

In [36]:
# Subtract
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out PyTorch in-built functions
torch.mul(tensor,10), torch.multiply(tensor,10)

(tensor([10, 20, 30]), tensor([10, 20, 30]))

In [38]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two ways of performing matrix multiplication in NNs and deep learning:

      1. Element-wise Multiplication
      2. Matrix multiplication (dot product)

Two main rules for matrix multiplication 
1. The **inner dimensions** must match:
    * `(n,m) @ (m,n)` Can use @ or matmul
2. The resulting matrix has the shape of the **outer dimensions**:
    * `(n,m) @ (m,n) = (n,n)`

In [39]:
# Element-wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [40]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [41]:
tensor

tensor([1, 2, 3])

In [42]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3
tensor @ tensor

tensor(14)

In [43]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 4.22 ms, sys: 0 ns, total: 4.22 ms
Wall time: 16.9 ms


In [44]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 84 µs, sys: 0 ns, total: 84 µs
Wall time: 88.2 µs


tensor(14)

### One of the most common errors in deep learning - shape errors

In [45]:
# Shapes for multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

#Trying matrix multiplication on these two tensors will not work due to shapes, so transpose one of them
torch.mm(tensor_A,tensor_B.T) # torch.mm is an alias for torch.matmul (same thing)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [46]:
# Matrix multiplication with correct shapes
print(f"The original shapes: Tensor_A = {tensor_A.shape}, Tensor_B = {tensor_B.shape}")
print(f"The new sahapes: Tensor_A = {tensor_A.shape} (same shape), Tensor_B = {tensor_B.T.shape} (transpose of tensor_B)")
print("The output is:\n")
output = torch.mm(tensor_A,tensor_B.T)
print(output)
print(f"\nThe output shape is: {output.shape}")

The original shapes: Tensor_A = torch.Size([3, 2]), Tensor_B = torch.Size([3, 2])
The new sahapes: Tensor_A = torch.Size([3, 2]) (same shape), Tensor_B = torch.Size([2, 3]) (transpose of tensor_B)
The output is:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

The output shape is: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc. (tensor aggregation)

In [47]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [48]:
# Min
torch.min(x), min(x)

(tensor(0), tensor(0))

In [49]:
# Max
torch.max(x), max(x)

(tensor(90), tensor(90))

In [50]:
# Mean (torch.mean() requires a tensor of float32 datatype to work)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [51]:
# Sum
torch.sum(x), sum(x)

(tensor(450), tensor(450))

## Finding the positional min and max (good to know if you want the location where a min or max occurs

In [52]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
# Find the position (index position) in the tensor that holds the minimum value with argmin()
x.argmin(), x[0]

(tensor(0), tensor(0))

In [54]:
# Find the position (index position) in the tensor that holds the maximum value with argmax()
x.argmax(), x[9]

(tensor(9), tensor(90))

### Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor a defined shape
* View - Return a view of an input tensor of a certain shape, but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze removes all `1` dimensions from a tensor
* Unsqueeze add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [55]:
# Create a tensor
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [56]:
# Reshape by adding an extra dimension (needs to be compatible with the original size)
x_reshaped_1 = x.reshape(1,10)
x_reshaped_2 = x.reshape(10,1)
x_reshaped_3 = x.reshape(5,2)
x_reshaped_4 = x.reshape(2,5)
x_reshaped_1, x_reshaped_1.shape, x_reshaped_2, x_reshaped_2.shape, x_reshaped_3, x_reshaped_3.shape, x_reshaped_4, x_reshaped_4.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]),
 tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]),
 tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]),
 tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [57]:
# Change the view
z = x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [58]:
# Changing z changes x since a view of a tensor shares the same memory as the original tensor
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [59]:
# Stack tensors on top of each other
x_stacked_1 = torch.stack([x,x,x,x],dim=0)
x_stacked_2 = torch.stack([x,x,x,x],dim=1)
x_stacked_1, x_stacked_2

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([[ 5.,  5.,  5.,  5.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]))

In [61]:
# torch.squeeze() removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped_1}")
print(f"Previous shape: {x_reshaped_1.shape}")

x_squeezed = x_reshaped_1.squeeze()
# Remove extra dimensions from x_reshaped
print(f"\nNew tensor: {x_squeezed}") 
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
New shape: torch.Size([10])


In [62]:
# torch.unsqueeze() adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
# Add an extra dimension
print(f"\nNew target: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

Previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New target: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

New shape: torch.Size([1, 10])


In [64]:
# torch.permute() rearranges the dimensions of a target tensor in a specified order (often used with images)
x_original = torch.rand(size=(224,224,3)) # height, width, color channels (rgb)

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # Shifts axis 0 -> 1, 1 -> 2, 2-> 0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color channels, height, width]


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [66]:
x_original[0,0,0] = 72818
x_original[0,0,0], x_permuted[0,0,0]

(tensor(72818.), tensor(72818.))

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [67]:
# Create tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [68]:
# Index on new tensor
# Index on the 0th dimension
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [70]:
# Index on middle bracket (dim = 1)
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [71]:
# Index on most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [74]:
# Can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [75]:
# Get all values of 0th and 1st dimensions, but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [76]:
# Get all values of the 0th dimension, but only the 1 index value of the 1st and 2nd dimension
# Gives back value in square bracket because we seleted all values of the 0th dimension (if x[0,1,1], we would get it without brackets )
x[:,1,1]

tensor([5])

In [77]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [91]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [92]:
# Index on x to return [3,6,9]
x[:,:,2]

tensor([[3, 6, 9]])

### PyTorch and NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarry)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`