<a href="https://colab.research.google.com/github/jfink09/Deep-Learning/blob/main/00_PyTorch_Fundamentals_Video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00 PyTroch Fundamentals

resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [2]:
import torch
print(torch.__version__) # Version 1.12 and Cuda 11.3

1.12.1+cu113


## Introduction to tensors

Tesors - a way to represent numerical data

PyTorch tensors are created using `torch.Tensor()` (https://pytorch.org/docs/stable/tensors.html)

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim # Scalars are a single number and do not have dimensions

0

In [5]:
scalar.item() # Get tensor back as Python int

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim # Vectors have one dimension

1

In [8]:
vector.shape # 2 elements in vector

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])

In [10]:
MATRIX.ndim # Two brackets

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape # One 3x3 matrix

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

NNs learn by starting with tensors full of random numbers and they adjust the random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6839, 0.0963, 0.1907, 0.2978],
        [0.0679, 0.2670, 0.3964, 0.5969],
        [0.9114, 0.2943, 0.7831, 0.8865]])

In [18]:
# Create random tensor with shape similar to image tensor
# Can use size=() or not including it creates similar tensors (size is not needed)
random_image_tensor = torch.rand(size=(224,224,3)) # Height, Width, Color Channel
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.range() if there is a depricated message use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the big three errors commonly run into in PyTorch and deep learning:

1. Tensors not the right datatype
2. Tensors not the right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Single-precision_floating-point_format

In [26]:
# Float 32 tensor (how much detail about the number is stored)
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype=torch.float16, # What datatype the tensor is (float16, float32, etc.)
                                device=None,         # What device is the tensor on, "cpu" by default (cand do "cuda")
                                requires_grad=False) # PyTorch can track the gradient of the tensor when it goes through calculations
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
# Convert float 32 into float 16 (good way to fix an error for a tensor being the wrong datatype)
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [29]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [30]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

1. Tensors not the right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not the right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [32]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5742, 0.1820, 0.5028, 0.6665],
        [0.7015, 0.2437, 0.5408, 0.5600],
        [0.0874, 0.3928, 0.4994, 0.2241]])

In [33]:
some_tensor.size() # Function/method with ()
some_tensor.shape  # Attribute

(torch.Size([3, 4]), torch.Size([3, 4]))

In [34]:
# Find some details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}") # torch.float32 is default
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is on: {some_tensor.device}") # CPU is default

tensor([[0.5742, 0.1820, 0.5028, 0.6665],
        [0.7015, 0.2437, 0.5408, 0.5600],
        [0.0874, 0.3928, 0.4994, 0.2241]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is on: cpu
